name: myshankara
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  go_router: ^16.3.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.12.0
  flutter_signin_button: ^2.1.1
  flutter_svg: ^2.2.1
  cloud_firestore: ^6.1.0
  flutter_timezone: ^5.0.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  app_settings: ^5.1.1
  fluttertoast: ^8.2.4
  mailer: ^6.1.0
  flutter_markdown_plus: ^1.0.12

flutter_icons:
  android: true
  ios: true
  image_path: assets/branding/logo.png

flutter_native_splash:
  color: "#FFF8F0"
  color_dark: "#F9F7FF"
  image: assets/branding/splash-logo.png
  android_12:
    color: "#FFF8F0"
    color_dark: "#F9F7FF"
    image: assets/branding/splash-logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/branding/logo.png
    - assets/branding/Logo-Trans.png
    - assets/branding/splash-logo.png
    - assets/backgrounds/home-background.jpg
    - assets/backgrounds/home-page-container1-image.jpg
    - assets/backgrounds/guruchatbg.png
    - assets/backgrounds/diya_tracker_background.png
    - assets/backgrounds/sunrise_background.png
    - assets/backgrounds/stir_background.png
    - assets/backgrounds/stir_popup_background.png
    - assets/backgrounds/back1.webp
    - assets/backgrounds/back2.webp
    - assets/backgrounds/back3.webp
    - assets/diya/diya-lit.png
    - assets/diya/diya-nlit.png
    - assets/diya/diya-darsan.png
    - assets/diya/diya-darsan-unlit.png
    - assets/diya/fire.png
    - assets/onboarding/onboarding-1.png
    - assets/onboarding/onboarding-2.png
    - assets/onboarding/onboarding-3.png
    - assets/onboarding/onboarding-4.png
    - assets/onboarding/screen-1.webp
    - assets/onboarding/screen3.png
    - assets/onboarding/2ndpaeg.png
    - assets/icons/om.png
    - assets/icons/om_icon.png
    - assets/icons/sunrise.png
    - assets/icons/google-icon-logo.svg
    - assets/icons/apple-logo.svg
    - assets/icons/nav/filled-chat.svg
    - assets/icons/nav/filled-home.svg
    - assets/icons/nav/filled-lotus.svg
    - assets/icons/nav/unfilled-chat.svg
    - assets/icons/nav/unfilled-home.svg
    - assets/icons/nav/unfilled-lotus.svg
    - assets/images/Guru-Chat.png
    - assets/images/ic_user_profile.jpeg

  fonts:
     - family: Samarkan
       fonts:
         - asset: assets/fonts/SAMAN.TTF
