// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCFlBbr3p4sjR8aiiV0VheXY9xg87IrCY',
    appId: '1:58392746649:android:1f306a0ef025cafd677608',
    messagingSenderId: '58392746649',
    projectId: 'first-firebase-project-c0d4a',
    storageBucket: 'first-firebase-project-c0d4a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClEd1sd8hZ7GVwVgnML5_1pqQYxjW5Mw8',
    appId: '1:58392746649:web:e65305d2478e63b4677608',
    messagingSenderId: '58392746649',
    projectId: 'first-firebase-project-c0d4a',
    authDomain: 'first-firebase-project-c0d4a.firebaseapp.com',
    storageBucket: 'first-firebase-project-c0d4a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbkdmwrdhxLFapWz_NgBuCL-oWF71u1sE',
    appId: '1:58392746649:ios:649201be3d0775cf677608',
    messagingSenderId: '58392746649',
    projectId: 'first-firebase-project-c0d4a',
    storageBucket: 'first-firebase-project-c0d4a.firebasestorage.app',
    iosBundleId: 'com.example.myshankara',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbkdmwrdhxLFapWz_NgBuCL-oWF71u1sE',
    appId: '1:58392746649:ios:649201be3d0775cf677608',
    messagingSenderId: '58392746649',
    projectId: 'first-firebase-project-c0d4a',
    storageBucket: 'first-firebase-project-c0d4a.firebasestorage.app',
    iosBundleId: 'com.example.myshankara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClEd1sd8hZ7GVwVgnML5_1pqQYxjW5Mw8',
    appId: '1:58392746649:web:37782cbafd400d60677608',
    messagingSenderId: '58392746649',
    projectId: 'first-firebase-project-c0d4a',
    authDomain: 'first-firebase-project-c0d4a.firebaseapp.com',
    storageBucket: 'first-firebase-project-c0d4a.firebasestorage.app',
  );

}